### ISSUE TITLE
AnimatedSticker messages are not supported by EFB Telegram Master channel.

### ISSUE THREAD

**Issue by zhou13** [scavin/docker-EFBv2#3]
您好！我用的你的docker的dev版本，但是依旧无法使用 AnimatedSticker，发sticker会返回
AnimatedSticker messages are not supported by EFB Telegram Master channel。这个是我的`docker-compose.yml`:
```
efbv2:
  image: scavin/docker-efbv2:dev
  container_name: efbv2
  restart: always
  dns: 8.8.8.8
  volumes:
    - ./:/root/.ehforwarderbot/profiles/default/
```
